### PR TITLE
fix: remove jsdom so polyfills arent needed.

### LINKED ISSUE #34: Can't work with Storybook + Webpack 5 starting 1.13.0
Hi,

Sorry in advance for the vague issue because I couldn't build a repro and the error logs are hard to decipher, but here it is:
- I am using Node 18
- Which forces me to use Webpack 5 in Storybook, Webpack 4 won't work
- The new peer deps to "@testing-library/dom" and in particular "jsdom" raises issues related to some variables not being polyfilled

Samples of the error log:
```
ModuleNotFoundError: Module not found: Error: Can't resolve 'stream' in '/home/ubuntu/webapp/node_modules/jsdom/lib/jsdom/living/helpers'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.


ModuleNotFoundError: Module not found: Error: Can't resolve 'perf_hooks' in '/home/ubuntu/webapp/node_modules/jsdom/lib/jsdom'
    at /home/ubuntu/webapp/node_modules/webpack/lib/Compilation.js:2016:28
    at /home/ubuntu/webapp/node_modules/webpack/lib/NormalModuleFactory.js:798:13
    at eval (eval at create (/home/ubuntu/webapp/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
```

Any idea where to start?

### PR DESCRIPTION
**Pull request by KonnorRogers**
Fixes #34

### CODE REVIEW

**Comment by CreativeTechGuy** [comment]
Just FYI, `DOMParser` is a browser API so it won't work in Node. It happens to still work here because JSDOM implements it. So in a roundabout way, this still depends on JSDOM globals being added. I think this sort of solves the problem since as long as this function isn't executed, it won't cause any problems. But if someone tries to execute this in a Node environment, it'll still crash as `DOMParser` doesn't exist.

**Comment by KonnorRogers** [comment]
@CreativeTechGuy  I think its a fair tradeoff only because I wouldn't expect to be running "DOM-testing-library" in an environment that wasn't at least JSDOM

**Comment by andyleanlibrary** [comment]
@CreativeTechGuy yep, that someone is me :-). This broke our tests, but adding jsdom in as a dependency fixed this.

**Comment by KonnorRogers** [comment]
Apologies @andyleanlibrary !

I'll add a note to the docs.

**Pull request merged**
